departments = {
    "Academic English": "AC ENG",
    "African American Studies": "AFAM",
    "Anatomy and Neurobiology": "ANATOMY",
    "Anesthesiology": "ANESTH",
    "Anthropology": "ANTHRO",
    "Arabic": "ARABIC",
    "Armenian": "ARMN",
    "Art": "ART",
    "Art History": "ART HIS",
    "Arts": "ARTS",
    "Arts and Humanities": "ARTSHUM",
    "Asian American Studies": "ASIANAM",
    "Business Analytics": "BANA",
    "Biomedical and Translational Science": "BATS",
    "Biological Sciences": "BIO SCI",
    "Biological Chemistry": "BIOCHEM",
    "Biomedical Engineering": "BME",
    "Campus Recreation": "CAMPREC",
    "Chemical and Biomolecular Engineering": "CBE",
    "Chemical Engr and Materials Science": "CBEMS",
    "Community and Environmental Medicine": "CEM",
    "Chicano Latino": "CHC%2FLAT",
    "Chemistry": "CHEM",
    "Chinese": "CHINESE",
    "Classics": "CLASSIC",
    "Culture & Theory": "CLT%26THY",
    "Cognitive Sciences": "COGS",
    "Comparative Literature": "COM LIT",
    "Computer Science": "COMPSCI",
    "Criticism": "CRITISM",
    "Criminology, Law and Society": "CRM%2FLAW",
    "Computer Science and Engineering": "CSE",
    "Dance": "DANCE",
    "Data Science": "DATA",
    "Dermatology": "DERM",
    "Developmental and Cell Biology": "DEV BIO",
    "Drama": "DRAMA",
    "East Asian Languages and Literatures": "E ASIAN",
    "Earth System Science": "EARTHSS",
    "East Asian Studies": "EAS",
    "Ecology and Evolutionary Biology": "ECO EVO",
    "Economics": "ECON",
    "Embedded and Cyber-Physical Systems": "ECPS",
    "Educational Affairs": "ED AFF",
    "Education": "EDUC",
    "Electrical Engineering & Computer Science": "EECS",
    "Environmental Health Sciences": "EHS",
    "English": "ENGLISH",
    "Engineering": "ENGR",
    "Engineering, Civil and Environmental": "ENGRCEE",
    "Engineering, Mechanical and Aerospace": "ENGRMAE",
    "Materials Science and Engineering": "ENGRMSE",
    "Epidemiology": "EPIDEM",
    "Emergency Medicine": "ER MED",
    "European Studies": "EURO ST",
    "Family Medicine": "FAM MED",
    "Finance": "FIN",
    "Film and Media Studies": "FLM%26MDA",
    "French": "FRENCH",
    "Game Design and Interactive Media": "GDIM",
    "Gender and Sexuality Studies": "GEN%26SEX",
    "German": "GERMAN",
    "Global Middle East Studies": "GLBL ME",
    "Global Cultures": "GLBLCLT",
    "Greek": "GREEK",
    "Hebrew": "HEBREW",
    "Hindi": "HINDI",
    "History": "HISTORY",
    "Humanities": "HUMAN",
    "Humanities and Arts": "HUMARTS",
    "Information and Computer Science": "I%26C SCI",
    "Informatics": "IN4MATX",
    "Masters of Innovation and Entrepreneurship": "INNO",
    "Internal Medicine": "INT MED",
    "International Studies": "INTL ST",
    "Iranian": "IRAN",
    "Japanese": "JAPANSE",
    "Korean": "KOREAN",
    "Latin": "LATIN",
    "Law": "LAW",
    "Linguistics": "LINGUIS",
    "Literary Journalism": "LIT JRN",
    "Logic and Philosophy of Science": "LPS",
    "Language Science": "LSCI",
    "Microbiology and Molecular Genetics": "M%26MO",
    "Mathematics": "MATH",
    "Medicine": "MED",
    "Medical Education": "MED ED",
    "Medical Humanities": "MED HUM",
    "Management": "MGMT",
    "Executive MBA": "MGMT EP",
    "Fully Employed MBA": "MGMT FE",
    "Health Care MBA": "HC",
    "Management MBA": "MGMTMBA",
    "Management PhD": "MGMTPHD",
    "Microbiology": "MIC BIO",
    "Molecular Biology and Biochemistry": "MOL BIO",
    "Accounting": "MPAC",
    "Materials Science and Engineering (Started 2020 Fall)": "MSE",
    "Networked Systems": "NET SYS",
    "Neurobiology and Behavior": "NEURBIO",
    "Neurology": "NEUROL",
    "Nursing Science": "NUR SCI",
    "Obstetrics and Gynecology": "OB%2FGYN",
    "Ophthalmology": "OPHTHAL",
    "Pathology and Laboratory Medicine": "PATH",
    "Pediatrics Genetics": "PED GEN",
    "Pediatrics": "PEDS",
    "Persian": "PERSIAN",
    "Pharmacology": "PHARM",
    "Philosophy": "PHILOS",
    "Pharmacy": "PHMD",
    "Pharmaceutical Sciences": "PHRMSCI",
    "Physical Science": "PHY SCI",
    "Physics": "PHYSICS",
    "Physiology and Biophysics": "PHYSIO",
    "Plastic Surgery": "PLASTIC",
    "Physical Medicine and Rehabilitation": "PM%26R",
    "Political Science": "POL SCI",
    "Portuguese": "PORTUG",
    "Planning, Policy, and Design": "PP%26D",
    "Psychological Science": "PSCI",
    "Psychology and Social Behavior": "PSY BEH",
    "Psychology": "PSYCH",
    "Public Policy ": "PUB POL",
    "Public Health": "PUBHLTH",
    "Radiology": "RADIO",
    "Religious Studies": "REL STD",
    "Reserve Officers' Training Corps": "ROTC",
    "Russian": "RUSSIAN",
    "Social Science": "SOC SCI",
    "Social Ecology": "SOCECOL",
    "Sociology": "SOCIOL",
    "Spanish": "SPANISH",
    "Social Policy & Public Service": "SPPS",
    "Statistics": "STATS",
    "Surgery": "SURGERY",
    "Software Engineering": "SWE",
    "Tagalog": "TAGALOG",
    "Toxicology": "TOX",
    "UC Washington DC": "UCDC",
    "University Affairs": "UNI AFF",
    "University Studies": "UNI STU",
    "Urban Planning and Public Policy": "UPPP",
    "Vietnamese": "VIETMSE",
    "Visual Studies": "VIS STD",
    "Writing": "WRITING"
  };

import re

def search_departments(query):
    results = {}
    pattern = re.compile(query, re.IGNORECASE)
    
    for department, code in departments.items():
        if re.search(pattern, department) or re.search(pattern, code):
            results[department] = code
    
    return results

user_query = input("Enter a department name or code: ")
search_results = search_departments(user_query)

if search_results:
    print("Search results:")
    for department, code in search_results.items():
        print(f"{department}: {code}")
else:
    print("No matching departments found.")