# Generated by Django 4.2.3 on 2023-08-10 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('class_type', models.CharField(blank=True, max_length=5000, null=True)),
                ('user', models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
