# Generated by Django 4.2.3 on 2023-08-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIdataStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=500)),
                ('api_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubscribedClasses',
        ),
    ]
