# Generated by Django 4.2.3 on 2023-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apidatastorage_delete_subscribedclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='department',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
