# Generated by Django 4.2.3 on 2023-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidatastorage',
            name='notification_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
