# Generated by Django 4.2.3 on 2023-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_apidatastorage_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=5000)),
                ('fullname', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
    ]
