# Generated by Django 4.2.3 on 2023-09-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_majors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Majors',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
