# Generated by Django 4.2.3 on 2023-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_majors_subscribers_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
