# Generated by Django 4.2.3 on 2023-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_planner_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
