# Generated by Django 4.2.3 on 2023-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_planner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
