# Generated by Django 4.2.3 on 2023-09-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_planner_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='start_year',
        ),
    ]
