# Generated by Django 4.2.3 on 2023-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_planner_end_year_remove_planner_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='type',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
