# Generated by Django 4.2.3 on 2023-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_planner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='major',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='major_url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
