# Generated by Django 4.2.3 on 2023-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_planner_major_planner_major_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
