# Generated by Django 4.2.3 on 2023-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_planner_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeplannertask',
            name='code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='timeplannertask',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
