# Generated by Django 4.2.3 on 2023-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_timeplannertask_code_timeplannertask_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeplannertask',
            name='course_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
