// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdp443Q5JQprmtRpZ7nzZYT9l0P5RBqUA',
    appId: '1:839458196232:web:a10a0d0f1c8f7bb41d3abd',
    messagingSenderId: '839458196232',
    projectId: 'notifyme-90d45',
    authDomain: 'notifyme-90d45.firebaseapp.com',
    databaseURL: 'https://notifyme-90d45-default-rtdb.firebaseio.com',
    storageBucket: 'notifyme-90d45.appspot.com',
    measurementId: 'G-JDCLLKKY0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKXOxKILfAKTskbuSwE8lquWdK10GX1ko',
    appId: '1:839458196232:android:b0de4a6523c88b251d3abd',
    messagingSenderId: '839458196232',
    projectId: 'notifyme-90d45',
    databaseURL: 'https://notifyme-90d45-default-rtdb.firebaseio.com',
    storageBucket: 'notifyme-90d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx80VOSh9_JvLFUOfGS1FEPJxG_ArArR8',
    appId: '1:839458196232:ios:46457f227ea440351d3abd',
    messagingSenderId: '839458196232',
    projectId: 'notifyme-90d45',
    databaseURL: 'https://notifyme-90d45-default-rtdb.firebaseio.com',
    storageBucket: 'notifyme-90d45.appspot.com',
    iosClientId: '839458196232-p1q38q4hlnm5unc3v92ncbpro060gk8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx80VOSh9_JvLFUOfGS1FEPJxG_ArArR8',
    appId: '1:839458196232:ios:46457f227ea440351d3abd',
    messagingSenderId: '839458196232',
    projectId: 'notifyme-90d45',
    databaseURL: 'https://notifyme-90d45-default-rtdb.firebaseio.com',
    storageBucket: 'notifyme-90d45.appspot.com',
    iosClientId: '839458196232-p1q38q4hlnm5unc3v92ncbpro060gk8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifyme',
  );
}
